#! /bin/bash
# This script is meant to evoke the algorithm without requiring any input arguments
#

CONTAINER="[ scitran/parrec-mr-classifier ]"

FLYWHEEL_BASE=/flywheel/v0

# Make sure that /output directory is empty (all content will be removed later).
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input/parrec

set -e

# Check if the inputs are empty.
if [[ -z $@ ]]
    then
      input_file=`find $INPUT_DIR -type f -name "*.zip*" | head -1`
      if [[ -n $input_file ]]
        then
            PYHONPATH=$PYTHONPATH:/flywheel/v0/ python $FLYWHEEL_BASE/parrec-mr-classifier.py "$input_file" "$OUTPUT_DIR"
      else
            echo -e "$INPUT_DIR has no valid input files!"
            exit 1
      fi
else
    # Run with input arguments
    PYHONPATH=$PYTHONPATH:/flywheel/v0/ python $FLYWHEEL_BASE/parrec-mr-classifier.py $@
fi


# Get a list of the files in the output directory
outputs=`find $OUTPUT_DIR -type f -name ".metadata.json"`


# Check for outputs
if [[ -z $outputs ]]
    then
        echo -e "$CONTAINER  No results found in output directory... Exiting"
        exit 1
    else
        chmod -R 777 $OUTPUT_DIR
        echo -e "$CONTAINER  Success."
fi

exit 0
